apiVersion: v1
kind: Pod
metadata:
  name: emptydir-bypass-test
spec:
  containers:
  - name: data-processor
    image: ubuntu:22.04
    command: ["/bin/sh", "-c"]
    args:
    - >
      echo "Writing 150MB to emptyDir Volume...";
      dd if=/dev/zero of=/data/largefile bs=1M count=150;
      sleep 3600
    resources:
      limits:
        ephemeral-storage: "100Mi"
    volumeMounts:
    - name: scratch-space
      mountPath: /data
  volumes:
  - name: scratch-space
    emptyDir: {}
