apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-root
  namespace: argocd
spec:
  project: shop-project
  source:
    repoURL: https://github.com/play-builder/linux-to-kubernetes.git
    targetRevision: main
    path: Ch_07_istio_ambient_service_mesh/07_03_istio_ambient_zero_trust/10-gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd            # 자식 Application이 생성될 곳
  syncPolicy:
    automated: { prune: true, selfHeal: true }
