apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-web
  labels:
    app: loadbalancer-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadbalancer-web
  template:
    metadata:
      labels:
        app: loadbalancer-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-web
spec:
  type: LoadBalancer # Triggers MetalLB to assign an EXTERNAL-IP
  selector:
    app: loadbalancer-web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
