# 07_03_istio_ambient_zero_trust/08-tests/00-nettest.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nettest
  namespace: shop
spec:
  restartPolicy: Never
  # 신원이 필요하면 spec.serviceAccountName: frontend 등을 추가
  containers:
  - name: nettest
    image: playbuilder/netshoot:latest
    command: ["curl", "-s", "http://frontend.shop.svc.cluster.local:8080"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
