# 07_03_istio_ambient_zero_trust/08-tests/01-mtls-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mtls-test
  namespace: shop
spec:
  restartPolicy: Never
  containers:
  - name: mtls-test
    image: playbuilder/netshoot:latest
    command: ["sh", "-c", "curl -s -o /dev/null -w '%{http_code}\\n' http://frontend.shop.svc.cluster.local:8080"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities: { drop: ["ALL"] }
      seccompProfile: { type: RuntimeDefault }
