apiVersion: v1
kind: Pod
metadata:
  name: authz-allow
  namespace: shop
spec:
  restartPolicy: Never
  serviceAccountName: frontend       # ← frontend 신원 사용
  containers:
  - name: authz-allow
    image: playbuilder/netshoot:latest
    command: ["sh", "-c", "curl -s -o /dev/null -w '%{http_code}\\n' http://api.shop.svc.cluster.local:8080/products"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities: { drop: ["ALL"] }
      seccompProfile: { type: RuntimeDefault }
