# 07_03_istio_ambient_zero_trust/08-tests/04-l7-allow.yaml
apiVersion: v1
kind: Pod
metadata:
  name: l7-allow
  namespace: shop
spec:
  restartPolicy: Never
  serviceAccountName: frontend
  containers:
  - name: l7-allow
    image: playbuilder/netshoot:latest
    command: ["sh", "-c", "curl -s -o /dev/null -w '%{http_code}\\n' http://api.shop.svc.cluster.local:8080/products"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities: { drop: ["ALL"] }
      seccompProfile: { type: RuntimeDefault }
