apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  namespace: shop
  labels:
    app: traffic-gen
spec:
  restartPolicy: Never
  containers:
  - name: traffic-gen
    image: playbuilder/netshoot:latest
    command: ["sh", "-c", "while true; do curl -s -o /dev/null http://frontend.shop.svc.cluster.local:8080; sleep 2; done"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
