apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: shop
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-db-credentials
  namespace: shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: api-db-secret
    creationPolicy: Owner
  data:
  - secretKey: db-password
    remoteRef:
      key: prod/shop/api
      property: db-password
