apiVersion: v1
kind: Pod
metadata:
  name: throttle-pod
  namespace: default
spec:
  containers:
  - name: stress
    image: playbuilder/stress:v1.0
    command: ["stress"]
    args: ["--cpu", "1"]
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
