# 07_03_istio_ambient_zero_trust/05-waypoint-l7/03-shop-access-logging.yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: shop-access-logging
  namespace: shop                # shop NS(waypoint 포함)에만 적용
spec:
  accessLogging:
  - providers:
    - name: envoy-accesslog      # istiod values(extensionProviders)에 정의한 이름과 일치 필수
