apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-waypoint-pdb
  namespace: shop
spec:
  minAvailable: 1               # drain 중에도 최소 1개 유지
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: api-waypoint
