# 07_03_istio_ambient_zero_trust/07-observability/05-telemetry.yaml
# mesh 전체 추적 활성화
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing         # extensionProviders와 일치
    randomSamplingPercentage: 1.0
---
# shop 네임스페이스 메트릭 라벨 커스터마이즈 (예시)
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: shop-metrics
  namespace: shop
spec:
  metrics:
  - providers:
    - name: prometheus
