apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  nodeName: wk1
  containers:
  - name: nginx-burstable
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
