apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  nodeName: wk2
  containers:
  - name: nginx-guaranteed
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
