apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ambient-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeName: wk2
      containers:
      - name: shell
        image: playbuilder/netshoot:latest
        command: ["sleep", "infinity"]
 
